### ISSUE TITLE
tour package 

### ISSUE THREAD

**Issue by alphapersian** [alphapersian/nasim_aseman_issue#2]
>@php_team
در سایت مبالغی که وارد میشوند باید دلار باشند و با علامت اختصاری .
usd - $ 
نمایش داده شوند در صورتی الان این مبالغ با علامت اختصاری ریال نمیاش داده میشوند 
![image](https://user-images.githubusercontent.com/5099477/34613852-8fe13a98-f244-11e7-9925-c54889be089f.png)

2.
نقشه مسیرها نمیاد

3.
Itinarary رو باید از کجا پرکنم
برنامه سفر باید بصورت پیش فرض روز اول - دوم و سوم و ... داشته باشه
و ما جای برنامه سفر رو پر کنید

![image](https://user-images.githubusercontent.com/5099477/34481071-372ae114-efc5-11e7-8ec0-ad9a7d395e62.png)

4.
. بعضی از تورهای چندین مقصد دارن، مثلا مشهد-تهران-قم و ... گزینه موقعیت به چه معنی می باشد
![image](https://user-images.githubusercontent.com/5099477/34481050-1d6506f6-efc5-11e7-913d-73e1391a24d6.png)

5.
![image](https://user-images.githubusercontent.com/5099477/35777051-63d73f44-09bc-11e8-94ec-21333790b03d.png)

6. 
![image](https://user-images.githubusercontent.com/5099477/35777055-814978b2-09bc-11e8-9982-1677f71422da.png)

7.
![image](https://user-images.githubusercontent.com/5099477/35777090-e6a27b32-09bc-11e8-8329-460ba77244e2.png)
 
8.
![image](https://user-images.githubusercontent.com/5099477/35777178-ac17bc00-09be-11e8-99b1-d2323fc06001.png)

9. 

-----------------
>@ui_team
1- 
![image](https://user-images.githubusercontent.com/5099477/35776999-7589e170-09bb-11e8-8fdf-3344eb37d54f.png)

2- 
![image](https://user-images.githubusercontent.com/5099477/35777023-e5df51e4-09bb-11e8-8dfb-f4ad3eb12598.png)

**Comment by birzad** [comment]
قیمت را به دلار شد.

**Comment by birzad** [comment]
نمایش نقشه مشکلی نداشت.
من  یه تصویر تستی زدم که جایگزین عکس فیل شد
سمت راست نمایش داد

**Comment by birzad** [comment]
برا ی Itinarary 
بعد از اینکه اطلاعات اصلی پکیج را وارد کردید از ستون برنامه سفر می توانید روز ها و برنامه های هر روز را وارد کنید.

**Comment by birzad** [comment]
امکان ایجاد رکوردهای پیش فرض 3 روز اول در حال حاضر نمی باشد.

**Comment by birzad** [comment]
**"بعضی از تورهای چندین مقصد دارن، مثلا مشهد-تهران-قم و ... گزینه موقعیت به چه معنی می باشد"**

در صورتی این فیلد پر شود، کاربر می تواند بر حسب استان پکیج تور ها  را فیلتر کند..

در حال حاضر با توجه به محتوایی که در سایت هست، فیلتر بر حسب دو استان 
qom, isfehan
امکان پذیر می باشد.

**Comment by birzad** [comment]
اصلاح شد.
رکوردهایی که نظر ندارند، باکس نمایش نظرشان غیر فعال شد

**Comment by birzad** [comment]
اصلاح شد.
تصویر آیکن پیش فرض برداشته شد و آیکن اصلی نمایش داده می شود.

**Comment by birzad** [comment]
اصلاح شد.

Prices / Date
در صورتی که حداقل یک رکورد در بخش 
low_season
یا
high_season

وجود داشته باشد این بخش نمایش داده می شود
در غیر این صورت محتوایی برای نمایش ندارد

**Comment by birzad** [comment]
مشکل نمایش لیست کشوئی فیلتر ها حل شد.
