### ISSUE TITLE
صفحه اصلی

### ISSUE THREAD

**Issue by alphapersian** [alphapersian/nasim_aseman_issue#4]
> @php_team

از صفحه اصلی منوهای  مشخص شده در تصویر قابل مشاهده نیستند 

![image](https://user-images.githubusercontent.com/5099477/34598960-0addee0c-f205-11e7-9d02-cf63059661cd.png)

با کلیک روی 
onlinebooking
یه سایت زیر هدایت شود 
http://tk.nasimaseman.ir/

![image](https://user-images.githubusercontent.com/5099477/34609265-41e8f726-f231-11e7-92a9-ca3f12d9e97b.png)

آدرس موجود برای 
tour package 
با آدرسی که از صفحات داخلی هدایت می شود متفاوت است 
 آدرسی که از صفحات داخلی به تور هدایت می شود  : http://nasimtourism.com/tour-package
آدرسی که از منوی اصلی هدایت میشود : http://nasimtourism.com/packages/Tour%20Package

--------------------

> @php_team

اخبار غیر قابل دسترس است 
![image](https://user-images.githubusercontent.com/5099477/34481315-b702b03c-efc6-11e7-83d6-e0fbf8676f39.png)

--------------

> @php_team

منوهای زبان به دو منو کاهش پیدا کنند و از منو فارسی به سایت نسیم آسمان فارسی هدایت شود 
http://www.nasimaseman.ir/

![image](https://user-images.githubusercontent.com/5099477/34481305-a913193a-efc6-11e7-95c5-6bc9883dca34.png)

---------------------------------

> @php_team

-------------------------------

> @php_team

**Comment by birzad** [comment]
مشکل لینک منو ها درست شد.

**Comment by birzad** [comment]
همه موارد انجام شد.

**Comment by alphapersian** [comment]
![image](https://user-images.githubusercontent.com/5099477/36478822-86b990fe-171b-11e8-9f0d-1535a5510f41.png)
@danaqom2017

**Comment by birzad** [comment]
بنده طبق UI
تحویل داده شده به من این کار را انجام دادم.
--------------------------
چهار خبر آخر را در این بخش قرار دادم
خانم کاظمی اسکریپت ها و css مربوطه را در این بخش قرار دهند.
