### ISSUE TITLE
iran visa

### ISSUE THREAD

**Issue by alphapersian** [alphapersian/nasim_aseman_issue#5]
> @ui_team

![image](https://user-images.githubusercontent.com/5099477/34599457-a38290fc-f207-11e7-8562-b6427357cece.png)
توضیحات در تصویر داده شده است 

-----------

> @php_team
![image](https://user-images.githubusercontent.com/5099477/34599611-85fc4ebe-f208-11e7-8e40-a7bda76875b9.png)
 در بخش iran embassies  سفارت خانه های ایران 
با کلیک روی هر سفات خانه باید اطلاعات تماس مربوط به آن سفارت خانه نمایش داده شود در صورتی که الان همه آیتم ها هم زمان نمایش داده شده اند .و از صفحه خارج شده اند 
 
-----------

> @php_team

![image](https://user-images.githubusercontent.com/5099477/34599714-0bb5f398-f209-11e7-9095-cc3fd0072f4e.png)

این مورد حتی در سایت سولار دیده شد 

---------------------------

> @ui_team

![image](https://user-images.githubusercontent.com/5099477/34599816-84d813a0-f209-11e7-8302-4a0c8376aa91.png)

 در طرح موارد در یک خط و به صورت عمودی مرتب شده اند در صورتی که اینجا مرتب نیست و آیتم های زیرین فاصله گرفته اند 
  

------------------

> @php_team

![image](https://user-images.githubusercontent.com/5099477/34600385-732cc968-f20c-11e7-926c-0d8b25dd89ec.png)

 توضیحات در تصویر داده شده اند 

-------------------

> @php_team

![image](https://user-images.githubusercontent.com/5099477/34600554-68361590-f20d-11e7-8e19-a08122cf577f.png)

قیمت ها وارد شده اند ولی نمایش داده نمی شوند 

-------------------------------

> @php_team

![image](https://user-images.githubusercontent.com/5099477/34600644-b77b4b70-f20d-11e7-8ed1-96f5f6abf8ca.png)

در تصویر بالا غلط املایی وجود دارد 
در جاهای دیگر بعضا غلط های املایی وجود دارد 
از کجا میتوان این غلط های املایی را تصحیح کرد 
  
---------------

> @ui_team
![image](https://user-images.githubusercontent.com/5099477/34600941-1c0f0698-f20f-11e7-8e8c-8a53695021dc.png)
 توضیحات در تصویر موجود است 

--------------

> @php_team

![image](https://user-images.githubusercontent.com/5099477/34600982-5744b9ba-f20f-11e7-945b-3a344d14cbd1.png)
 توضیحات در تصویر موجود است 
این تصویر برای بخش بدون ویزا هست
دقت کنید در این تصویر نیز غلط املایی وجود دارد که باید اصلاح شود 

---------------------

>@php_team

![image](https://user-images.githubusercontent.com/5099477/34601089-b43c448a-f20f-11e7-840b-ec41208edf91.png)
  
تمامی قیمت ها در این سایت به دلار هستند 
لطفا به جای علامت اختصاری ریال از علامت اختصاری دلار استفاده کنید 

---------------------

>@php_team
 
![image](https://user-images.githubusercontent.com/5099477/35777786-217a863a-09c9-11e8-9c81-220119c7752b.png)

**Comment by birzad** [comment]
مشکل دو خطی شدن منو حل شد.

**Comment by birzad** [comment]
مشکل کلیک روی هر سفارت خانه مربوط به تیم 
ui
می شود.

**Comment by birzad** [comment]
موردی که مشابه سایت سولار بود حل شد.

**Comment by birzad** [comment]
مشکل نمایش اطلاعات مربوط به ویزاهای فرودگاهی
مشابه مشکل نمایش سفارت خانه ها است
که بر عهده تیم ui
می باشد.

**Comment by birzad** [comment]
مشکل عدم نمایش قیمت ویزاها درست شد.

**Comment by birzad** [comment]
غلط املائی:
با توجه به آنجه که تیم ui به بنده داده بود پیاده سازی کردم.
----------------------------------------------
راه حل غلط املائی ها این است که یک لغت نامه درست کنیم که معمولا بعد از اینکه سایت چندزبانه شد، این ماژول را هم اجرائی می کنیم.

**Comment by birzad** [comment]
مشکل کشورهای بدون ویزا تکراری هست.
مورد مربوط به تیم ui

**Comment by birzad** [comment]
نمایش هزینه ها با علامت اختصاری $
تغییر یافت

**Comment by birzad** [comment]
برای کشور هایی که چندتا سفارت خانه دارد باید به تعداد آنها اطلاعات وارد کنید.
مثلا برای عراق 4 رکورد با اطلاعات تماس متفاوت ثبت کنید و فیلد قاره و کشور را به صورت یکسان ثبت کنید.
برای اینکه دو رکورد هنگام نمایش کنار هم قرار بگیریند ترتیب نمایش آنها را با یک عدد یکسان تعیین کنید.
